name: bdd_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  gherkin: ^1.1.9

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/